name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Build with Gradle
      run: gradle jar sourcesJar javadocJar socialsdk4jSharedLibrary test
    - name: Upload Linux Natives
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux-natives
        path: socialsdk4j/build/libs/socialsdk4j/shared/libsocialsdk4j.so
        error: true
    - name: Upload Jars
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux-natives
        path: socialsdk4j/build/libs/socialsdk4j-*.jar
        error: true

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Build with Gradle
      run: gradle jar socialsdk4jSharedLibrary test
    - name: Upload macOS Natives
      uses: actions/upload-artifact@v4.6.2
      with:
        name: macos-natives
        path: socialsdk4j/build/libs/socialsdk4j/shared/libsocialsdk4j.dylib
        error: true
    
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Build with Gradle
      run: gradle jar socialsdk4jSharedLibrary test
    - name: Upload Windows Natives
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-natives
        path: socialsdk4j/build/libs/socialsdk4j/shared/socialsdk4j.dll
        error: true

  build:
    needs:
    - build-linux
    - build-macos
    - build-windows

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Download artifacts
      uses: actions/download-artifact@v4.3.0
      with:
        merge-multiple: true

    - name: List
      run: |
        ls -l

    - name: Build with Gradle
      run: gradle publish

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
