name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Build with Gradle
      run: gradle jar sourcesJar javadocJar socialsdk4jSharedLibrary test
    - name: Upload Linux Natives
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux-natives
        path: build/libs/socialsdk4j/shared/libsocialsdk4j.so
        if-no-files-found: error
    - name: Upload Jars
      uses: actions/upload-artifact@v4.6.2
      with:
        name: jars
        path: build/libs/socialsdk4j-*.jar
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Build with Gradle
      run: gradle jar socialsdk4jSharedLibrary test
    - name: Upload macOS Natives
      uses: actions/upload-artifact@v4.6.2
      with:
        name: macos-natives
        path: build/libs/socialsdk4j/shared/libsocialsdk4j.dylib
        if-no-files-found: error
    
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Build with Gradle
      run: gradle jar socialsdk4jSharedLibrary test
    - name: Upload Windows Natives
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-natives
        path: build/libs/socialsdk4j/shared/socialsdk4j.dll
        if-no-files-found: error

  build:
    needs:
    - build-linux
    - build-macos
    - build-windows

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    if: github.ref_name == 'master' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Download artifacts
      uses: actions/download-artifact@v4.3.0
      with:
        merge-multiple: true

    - name: List
      run: |
        ls -l

    - name: Place natives in correct locations
      run: |
        mkdir -p build/libs/socialsdk4j/shared
        cp *.so *.dylib *.dll build/libs/socialsdk4j/shared/

    - name: Build with Gradle
      run: gradle -Dci=yes publishMavenPublicationToGitHubPackagesRepository publishBomPublicationToGitHubPackagesRepository
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
