name: Publish new SocialSDK version with Gradle

on:
  push:
    branches: [ "master" ]
    paths:
      - discord-social-sdk.zip

jobs:
  publish-socialsdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.1'

    - name: Build with Gradle
      run: gradle -Dci=yes publishSocialSDKPublicationToTestDeployRepository publishSocialSDKDebugPublicationToTestDeployRepository
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
